### ISSUE TITLE
Captive portals

### ISSUE THREAD

**Issue by eloydegen** [d33tah/call-for-wpa3#8]
The problem of the captive portals is actually solved, but through [DHCP](https://tools.ietf.org/html/rfc7710).

They added a new option (number 160 for IPv4 and 103 for IPv6) to inform the client requesting an address that there is a portal on the specified URL.

Regards,

That Dutch guy who tasted some of your Tschunk at the SHA bar :)

**Comment by d33tah** [comment]
Hi @eloydegen! Nice to see you here, sorry I missed your message. Does anybody actually use the DHCP advertisement of captive portals?
